services:
  app:
    container_name: drop-app
    build: ./app
    environment:
      - APP_URL=https://127.0.0.1:8000
      - DATABASE_URL=database:5432
      - DATABASE_PASSWORD=123456789
    ports:
      - "8000:8000"
    networks:
      - drop

  database:
    container_name: database
    image: postgres:18
    environment:
      - POSTGRES_PASSWORD=123456789
    ports:
      - "5432:5432"
    networks:
      - drop
    volumes:
      - drop_database:/var/lib/postgresql

networks:
  drop:

volumes:
  drop_database: