[project]
name = "app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Pasha", email = "p@past5578.dev" }
]
requires-python = ">=3.14"
dependencies = [
    "asyncpg>=0.31.0",
    "fastapi[standard]>=0.141.1",
    "pillow>=12.3.0",
    "python-dotenv>=1.2.3",
    "python-multipart>=0.0.32",
]

[project.scripts]
app = "app:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
